const crypto = require('crypto');
const { PDFDocument, StandardFonts, rgb } = require('pdf-lib');

/**
 * Appends a fake "signature audit" page to the original PDF, loosely modeled
 * after what Autentique embeds in a real signed document (per-signer info,
 * timestamp, IP/geolocation, a hash of the file). There is no real sample to
 * copy the actual layout from, so this only approximates the *data*, not
 * Autentique's visual design - and it says so, in giant letters, so nobody
 * mistakes it for a real certificate.
 */
async function buildSignedPdf(originalBuffer, { documentId, signers }) {
    const pdfDoc = await PDFDocument.load(originalBuffer);
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const page = pdfDoc.addPage();
    const { height } = page.getSize();
    let y = height - 60;

    const hash = crypto.createHash('sha256').update(originalBuffer).digest('hex');

    page.drawText('SIMULATED DOCUMENT - NOT A REAL AUTENTIQUE CERTIFICATE', {
        x: 40, y, size: 14, font: boldFont, color: rgb(0.8, 0, 0),
    });
    y -= 30;

    page.drawText(`Document ID: ${documentId}`, { x: 40, y, size: 10, font });
    y -= 16;
    page.drawText(`Original file SHA-256: ${hash}`, { x: 40, y, size: 10, font });
    y -= 16;
    page.drawText(`Generated at: ${new Date().toISOString()}`, { x: 40, y, size: 10, font });
    y -= 30;

    page.drawText('Signatures', { x: 40, y, size: 12, font: boldFont });
    y -= 20;

    signers.forEach((signer) => {
        const label = signer.name || signer.email || signer.phone || signer.public_id;
        page.drawText(`- ${label} (${signer.action})`, { x: 50, y, size: 10, font });
        y -= 14;
        page.drawText(`  signed_at: ${signer.signed_at}`, { x: 50, y, size: 9, font, color: rgb(0.3, 0.3, 0.3) });
        y -= 14;
        page.drawText('  ip: 203.0.113.42  geolocation: Sao Paulo, BR (simulated)', {
            x: 50, y, size: 9, font, color: rgb(0.3, 0.3, 0.3),
        });
        y -= 20;
    });

    page.drawText('This page was generated by a local mock for development purposes only.', {
        x: 40, y: 40, size: 8, font, color: rgb(0.5, 0.5, 0.5),
    });

    return Buffer.from(await pdfDoc.save());
}

module.exports = { buildSignedPdf };
